-- WeldHub moderation: approvals, abuse reports, user blocks and audit history.

alter table public.companies
  add column if not exists moderation_status text not null default 'pending',
  add column if not exists moderation_note text,
  add column if not exists moderated_at timestamptz,
  add column if not exists moderated_by uuid references auth.users(id) on delete set null;

alter table public.companies
  drop constraint if exists companies_moderation_status_check;
alter table public.companies
  add constraint companies_moderation_status_check
  check (moderation_status in ('pending', 'approved', 'rejected'));

-- Existing public profiles have already been visible and remain visible.
update public.companies
set moderation_status = case when status = 'published' then 'approved' else 'pending' end
where moderation_status = 'pending';

alter table public.requests
  add column if not exists moderation_status text not null default 'visible',
  add column if not exists moderation_note text,
  add column if not exists moderated_at timestamptz,
  add column if not exists moderated_by uuid references auth.users(id) on delete set null;

alter table public.requests
  drop constraint if exists requests_moderation_status_check;
alter table public.requests
  add constraint requests_moderation_status_check
  check (moderation_status in ('visible', 'hidden'));

create table if not exists public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

create table if not exists public.blocked_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  reason text not null default 'Naruszenie zasad WeldHub',
  blocked_at timestamptz not null default now(),
  blocked_by uuid references auth.users(id) on delete set null
);

create table if not exists public.moderation_reports (
  id bigint generated by default as identity primary key,
  reporter_id uuid not null references auth.users(id) on delete cascade,
  target_type text not null check (target_type in ('company', 'request')),
  target_id bigint not null,
  reason text not null check (char_length(reason) between 3 and 80),
  details text check (details is null or char_length(details) <= 2000),
  status text not null default 'open' check (status in ('open', 'resolved', 'dismissed')),
  resolution_note text,
  resolved_at timestamptz,
  resolved_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

create table if not exists public.moderation_audit_log (
  id bigint generated by default as identity primary key,
  admin_id uuid not null references auth.users(id) on delete restrict,
  action text not null,
  target_type text not null,
  target_id text not null,
  note text,
  created_at timestamptz not null default now()
);

create index if not exists companies_moderation_queue_idx
  on public.companies (moderation_status, created_at desc);
create index if not exists requests_moderation_queue_idx
  on public.requests (moderation_status, created_at desc);
create index if not exists moderation_reports_queue_idx
  on public.moderation_reports (status, created_at desc);
create index if not exists moderation_audit_log_created_at_idx
  on public.moderation_audit_log (created_at desc);

-- Bootstrap the WeldHub operator if this account already exists.
insert into public.admin_users (user_id)
select id from auth.users where lower(email) = 'weldhub@fastmail.com'
on conflict (user_id) do nothing;

create or replace function private.is_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1 from public.admin_users where user_id = (select auth.uid())
  );
$$;

create or replace function private.is_blocked()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1 from public.blocked_users where user_id = (select auth.uid())
  );
$$;

revoke all on function private.is_admin() from public;
revoke all on function private.is_blocked() from public;
grant usage on schema private to authenticated;
grant execute on function private.is_admin() to authenticated;
grant execute on function private.is_blocked() to authenticated;

alter table public.admin_users enable row level security;
alter table public.blocked_users enable row level security;
alter table public.moderation_reports enable row level security;
alter table public.moderation_audit_log enable row level security;

revoke all on table public.admin_users from anon, authenticated;
revoke all on table public.blocked_users from anon, authenticated;
revoke all on table public.moderation_reports from anon, authenticated;
revoke all on table public.moderation_audit_log from anon, authenticated;

grant select on table public.admin_users to authenticated;
grant select on table public.blocked_users to authenticated;
grant select, insert on table public.moderation_reports to authenticated;
grant select on table public.moderation_audit_log to authenticated;
grant usage, select on sequence public.moderation_reports_id_seq to authenticated;

create policy admin_users_self_read on public.admin_users
for select to authenticated using (user_id = (select auth.uid()));

create policy blocked_users_self_or_admin_read on public.blocked_users
for select to authenticated
using (user_id = (select auth.uid()) or private.is_admin());

create policy reports_submit on public.moderation_reports
for insert to authenticated
with check (reporter_id = (select auth.uid()) and not private.is_blocked());

create policy reports_own_or_admin_read on public.moderation_reports
for select to authenticated
using (reporter_id = (select auth.uid()) or private.is_admin());

create policy audit_admin_read on public.moderation_audit_log
for select to authenticated using (private.is_admin());

-- Public profiles must be approved. Owners retain private access to their queue state.
drop policy if exists companies_public_read on public.companies;
create policy companies_public_read on public.companies
for select to anon
using (status = 'published' and moderation_status = 'approved');

drop policy if exists companies_authenticated_read on public.companies;
create policy companies_authenticated_read on public.companies
for select to authenticated
using (
  (status = 'published' and moderation_status = 'approved')
  or owner_id = (select auth.uid())
  or private.can_customer_view_company(id)
  or private.is_admin()
);

drop policy if exists companies_owner_insert on public.companies;
create policy companies_owner_insert on public.companies
for insert to authenticated
with check (owner_id = (select auth.uid()) and not private.is_blocked());

drop policy if exists companies_owner_update on public.companies;
create policy companies_owner_update on public.companies
for update to authenticated
using (owner_id = (select auth.uid()) and not private.is_blocked())
with check (owner_id = (select auth.uid()) and not private.is_blocked());

drop policy if exists companies_owner_delete on public.companies;
create policy companies_owner_delete on public.companies
for delete to authenticated
using (owner_id = (select auth.uid()) and not private.is_blocked());

create or replace function private.queue_company_after_change()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if (select auth.jwt() ->> 'role') = 'service_role' then
    return new;
  end if;

  if tg_op = 'INSERT' then
    new.moderation_status := 'pending';
    new.moderation_note := null;
    new.moderated_at := null;
    new.moderated_by := null;
  elsif row(
    new.name, new.description, new.phone, new.email, new.website, new.logo_url,
    new.address, new.city, new.region, new.services, new.materials,
    new.welding_methods, new.google_place_id
  ) is distinct from row(
    old.name, old.description, old.phone, old.email, old.website, old.logo_url,
    old.address, old.city, old.region, old.services, old.materials,
    old.welding_methods, old.google_place_id
  ) then
    new.moderation_status := 'pending';
    new.moderation_note := null;
    new.moderated_at := null;
    new.moderated_by := null;
  else
    new.moderation_status := old.moderation_status;
    new.moderation_note := old.moderation_note;
    new.moderated_at := old.moderated_at;
    new.moderated_by := old.moderated_by;
  end if;

  return new;
end;
$$;

drop trigger if exists queue_company_after_change on public.companies;
create trigger queue_company_after_change
before insert or update on public.companies
for each row execute function private.queue_company_after_change();
revoke all on function private.queue_company_after_change() from public;

-- Only visible public requests are exposed by the privacy-safe listing view.
drop view if exists public.public_request_listings;
create view public.public_request_listings
with (security_barrier = true, security_invoker = false)
as
select
  id, created_at, category, description, city, request_type, status,
  title, image_url, image_urls, company_id
from public.requests
where company_id is null
  and status in ('new', 'contacting')
  and moderation_status = 'visible';

revoke all on table public.public_request_listings from public, anon, authenticated;
grant select on table public.public_request_listings to anon, authenticated;

-- Prevent blocked accounts from changing records through the browser client.
drop policy if exists requests_customer_or_target_update on public.requests;
create policy requests_customer_or_target_update on public.requests
for update to authenticated
using (
  not private.is_blocked()
  and (customer_id = (select auth.uid()) or private.is_target_company_owner(id))
)
with check (
  not private.is_blocked()
  and (customer_id = (select auth.uid()) or private.is_target_company_owner(id))
);

drop policy if exists company_images_owner_insert on public.company_images;
create policy company_images_owner_insert on public.company_images
for insert to authenticated
with check (not private.is_blocked() and private.is_company_owner(company_id));

drop policy if exists company_images_owner_update on public.company_images;
create policy company_images_owner_update on public.company_images
for update to authenticated
using (not private.is_blocked() and private.is_company_owner(company_id))
with check (not private.is_blocked() and private.is_company_owner(company_id));

drop policy if exists company_images_owner_delete on public.company_images;
create policy company_images_owner_delete on public.company_images
for delete to authenticated
using (not private.is_blocked() and private.is_company_owner(company_id));

drop policy if exists company_images_public_read on public.company_images;
create policy company_images_public_read on public.company_images
for select to anon
using (
  exists (
    select 1 from public.companies as company
    where company.id = company_images.company_id
      and company.status = 'published'
      and company.moderation_status = 'approved'
  )
);

drop policy if exists company_images_authenticated_read on public.company_images;
create policy company_images_authenticated_read on public.company_images
for select to authenticated
using (
  exists (
    select 1 from public.companies as company
    where company.id = company_images.company_id
      and company.status = 'published'
      and company.moderation_status = 'approved'
  )
  or private.is_company_owner(company_id)
  or private.is_admin()
);

drop policy if exists whub_company_assets_upload on storage.objects;
create policy whub_company_assets_upload
on storage.objects
for insert to authenticated
with check (
  not private.is_blocked()
  and bucket_id in ('logos', 'company_logos', 'company_images')
  and coalesce((metadata ->> 'size')::bigint, 0) <= 8388608
  and coalesce(metadata ->> 'mimetype', '') like 'image/%'
  and (storage.foldername(name))[1] ~ '^[0-9]+$'
  and private.is_company_owner(((storage.foldername(name))[1])::bigint)
);

drop policy if exists whub_company_assets_update on storage.objects;
create policy whub_company_assets_update
on storage.objects
for update to authenticated
using (
  not private.is_blocked()
  and bucket_id in ('logos', 'company_logos', 'company_images')
  and (storage.foldername(name))[1] ~ '^[0-9]+$'
  and private.is_company_owner(((storage.foldername(name))[1])::bigint)
)
with check (
  not private.is_blocked()
  and bucket_id in ('logos', 'company_logos', 'company_images')
  and coalesce((metadata ->> 'size')::bigint, 0) <= 8388608
  and coalesce(metadata ->> 'mimetype', '') like 'image/%'
  and (storage.foldername(name))[1] ~ '^[0-9]+$'
  and private.is_company_owner(((storage.foldername(name))[1])::bigint)
);

drop policy if exists whub_company_assets_delete on storage.objects;
create policy whub_company_assets_delete
on storage.objects
for delete to authenticated
using (
  not private.is_blocked()
  and bucket_id in ('logos', 'company_logos', 'company_images')
  and (storage.foldername(name))[1] ~ '^[0-9]+$'
  and private.is_company_owner(((storage.foldername(name))[1])::bigint)
);
