-- Administrator-only staging area for company directory imports.

create table if not exists public.company_import_batches (
  id uuid primary key default gen_random_uuid(),
  file_name text not null check (char_length(file_name) between 1 and 255),
  total_rows integer not null default 0 check (total_rows >= 0),
  imported_rows integer not null default 0 check (imported_rows >= 0),
  duplicate_rows integer not null default 0 check (duplicate_rows >= 0),
  invalid_rows integer not null default 0 check (invalid_rows >= 0),
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

create table if not exists public.company_leads (
  id bigint generated by default as identity primary key,
  import_batch_id uuid references public.company_import_batches(id) on delete set null,
  source_row integer check (source_row is null or source_row > 1),
  name text not null check (char_length(name) between 2 and 160),
  nip text check (nip is null or nip ~ '^[0-9]{10}$'),
  city text not null check (char_length(city) between 1 and 120),
  region text check (region is null or char_length(region) <= 120),
  address text check (address is null or char_length(address) <= 240),
  phone text check (phone is null or char_length(phone) <= 40),
  email text check (email is null or char_length(email) <= 254),
  website text check (website is null or char_length(website) <= 500),
  services text[] not null default '{}',
  services_raw text[] not null default '{}',
  materials text[] not null default '{}',
  welding_methods text[] not null default '{}',
  service_area text check (service_area is null or char_length(service_area) <= 120),
  mobile_service boolean not null default false,
  source_url text not null check (char_length(source_url) between 8 and 500),
  notes text check (notes is null or char_length(notes) <= 1000),
  status text not null default 'new'
    check (status in (
      'new', 'to_verify', 'contacted', 'consent_received', 'declined',
      'converted', 'archived'
    )),
  privacy_notice_sent_at timestamptz,
  consent_at timestamptz,
  linked_company_id bigint unique references public.companies(id) on delete set null,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists company_import_batches_created_at_idx
  on public.company_import_batches (created_at desc);
create index if not exists company_leads_status_created_at_idx
  on public.company_leads (status, created_at desc);
create index if not exists company_leads_nip_idx
  on public.company_leads (nip) where nip is not null;
create index if not exists company_leads_name_city_idx
  on public.company_leads (lower(name), lower(city));

alter table public.company_import_batches enable row level security;
alter table public.company_leads enable row level security;

-- These tables are intentionally unavailable through the public Supabase API.
-- The application accesses them only with the service role after an admin check.
revoke all on table public.company_import_batches from anon, authenticated;
revoke all on table public.company_leads from anon, authenticated;
revoke all on sequence public.company_leads_id_seq from anon, authenticated;

